In [92]:
import pandas as pd
import glob
import os

In [93]:
folder_path = r'C:\Users\isabe\PycharmProjects\GSB-503-Engie-1\Data\DAM 60d ERCOT'
csv_files = glob.glob(folder_path + '/*.csv')

# Dictionary to store DataFrames with unique names
dataframes = {}

# Iterate over the list of CSV files
for i, file in enumerate(csv_files, start=1):
    # Read the CSV file
    df = pd.read_csv(file)
    
    # Extract the base name of the file (without path and extension)
    base_name = os.path.basename(file).replace('.csv', '')
    
    # Create a unique name for the DataFrame
    unique_name = f"df_{base_name}"
    
    # Store the DataFrame in the dictionary
    dataframes[unique_name] = df

for name, df in dataframes.items():
    print(f"{name} shape: {df.shape}")

df_dam_energybids_60d shape: (33245, 28)
df_dam_energyonlyofferawards_60d shape: (20416, 8)
df_dam_energyonlyoffers_60d shape: (20416, 28)
df_dam_generation_resource_asoffers_60d shape: (8433, 62)
df_dam_gen_resource_data_60d shape: (33720, 50)
df_dam_load_resource_asoffers_60d shape: (7250, 63)
df_dam_load_resource_data_60d shape: (16104, 20)
df_dam_ptpobligationbidawards_60d shape: (196370, 9)
df_dam_ptpobligationbids_60d shape: (196370, 10)
df_dam_ptp_obligation_optionawards_60d shape: (8833, 10)
df_dam_ptp_obligation_option_60d shape: (8833, 11)
df_dam_qse_self_arranged_as_60d shape: (840, 13)

In [94]:
offer_awards = dataframes['df_dam_energyonlyofferawards_60d']
energy_offers = dataframes['df_dam_energyonlyoffers_60d']
energy_offers.rename(columns={'energy_only_offer_id': 'offer_id'}, inplace=True)

merged_data = offer_awards.merge(
    energy_offers,
    on=['delivery_date', 'hour_ending', 'settlement_point', 'qse_name', 'p_posted_date', 'offer_id'],
    how='outer'
)

In [95]:
merged_data

,delivery_date,hour_ending,settlement_point,qse_name,energy_only_offer_award_in_mw,settlement_point_price,offer_id,p_posted_date,energy_only_offer_mw1,energy_only_offer_price1,...,energy_only_offer_mw7,energy_only_offer_price7,energy_only_offer_mw8,energy_only_offer_price8,energy_only_offer_mw9,energy_only_offer_price9,energy_only_offer_mw10,energy_only_offer_price10,multi_hour_block_indicator,block/curve_indicator
0,2024-10-02,1,AEEC,QGRAN3,0.0,10.83,KJC9ejaKao,2024-12-01,13.3,47.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,V
1,2024-10-02,1,AEEC,QGRAN3,0.0,10.83,fvBW7zmVrc,2024-12-01,10.2,38.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,V
2,2024-10-02,1,AEEC,QGRIEQ,0.0,10.83,c7knxw,2024-12-01,25.0,18.16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,C
3,2024-10-02,1,AEEC,QGRIEQ,3.4,10.83,ho0f8z,2024-12-01,3.4,-13.73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,C
4,2024-10-02,1,AGUAYO_UNIT1,QPEBSE,0.0,24.48,NTL01,2024-12-01,1.0,31.30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20411,2024-10-02,24,WNDTS2_UNIT1,QCOMIT,2.4,15.85,222855132,2024-12-01,2.4,-250.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,V
20412,2024-10-02,24,WNDTS2_UNIT1,QCWPE2,0.0,15.85,eQ7xhRTM,2024-12-01,10.0,29.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,C
20413,2024-10-02,24,WNDTS2_UNIT1,QTENSK,2.7,15.85,WT2DAOptEO,2024-12-01,2.7,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,V
20414,2024-10-02,24,WNDTS2_UNIT1,QTHORD,2.0,15.85,11,2024-12-01,2.0,-11.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,V
20415,2024-10-02,24,YNG_WND_ALL,QFPLE4,65.1,13.46,YNG01,2024-12-01,65.1,-38.76,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,V

In [96]:
energy_bids = dataframes['df_dam_energybids_60d']

merged_data = merged_data.merge(
    energy_bids,
    on=['delivery_date', 'hour_ending', 'settlement_point', 'qse_name', 'p_posted_date',
        'multi_hour_block_indicator', 'block/curve_indicator'],
    how='outer'
)

merged_data.head()

,delivery_date,hour_ending,settlement_point,qse_name,energy_only_offer_award_in_mw,settlement_point_price,offer_id,p_posted_date,energy_only_offer_mw1,energy_only_offer_price1,...,energy_only_bid_price6,energy_only_bid_mw7,energy_only_bid_price7,energy_only_bid_mw8,energy_only_bid_price8,energy_only_bid_mw9,energy_only_bid_price9,energy_only_bid_mw10,energy_only_bid_price10,energy_only_bid_id
0,2024-10-02,1,AEEC,QAUROR,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55dd3af0-c73
1,2024-10-02,1,AEEC,QGRAN3,0.0,10.83,KJC9ejaKao,2024-12-01,13.3,47.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-10-02,1,AEEC,QGRAN3,0.0,10.83,fvBW7zmVrc,2024-12-01,10.2,38.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-10-02,1,AEEC,QGRIEQ,0.0,10.83,c7knxw,2024-12-01,25.0,18.16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6yamiy
4,2024-10-02,1,AEEC,QGRIEQ,3.4,10.83,ho0f8z,2024-12-01,3.4,-13.73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6yamiy

In [97]:
gen_resource_data = dataframes['df_dam_gen_resource_data_60d']
gen_resource_data.rename(columns={'settlement_point_name': 'settlement_point', 'qse': 'qse_name'}, inplace=True)

merged_data = merged_data.merge(
    gen_resource_data,
    on=['delivery_date', 'hour_ending', 'qse_name', 'settlement_point',
        'p_posted_date'],
    how='outer'
)

In [98]:
merged_data

,delivery_date,hour_ending,settlement_point,qse_name,energy_only_offer_award_in_mw,settlement_point_price,offer_id,p_posted_date,energy_only_offer_mw1,energy_only_offer_price1,...,regdown_mcpc,rrs_awarded,rrs_mcpc,nonspin_awarded,nonspin_mcpc,rrspfr_awarded,rrsffr_awarded,rrsufr_awarded,ecrssd_awarded,ecrs_mcpc
0,2024-10-02,1,ARAGORN_RN,QAEN,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-10-02,1,BOOTLEG_UN1,QAEN,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-10-02,1,DECKER_GT,QAEN,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,0.79,NaN,0.75,48.0,0.2,0.0,0.0,0.0,0.0,0.05
3,2024-10-02,1,DECKER_GT,QAEN,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-10-02,1,DECKER_GT,QAEN,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93237,2024-10-02,24,WHCCS2_4,QZANDY,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93238,2024-10-02,24,WHCCS2_4,QZANDY,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93239,2024-10-02,24,WHCCS2_4,QZANDY,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93240,2024-10-02,24,WHCCS2_4,QZANDY,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93241,2024-10-02,24,CROSSETT_ALL,QZEPHY,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,0.69,NaN,0.79,0.0,0.5,10.6,0.0,0.0,0.0,0.07

In [99]:
gen_resource_data_as = dataframes['df_dam_generation_resource_asoffers_60d']
gen_resource_data_as.rename(columns={'generation_resource_name': 'resource_name', 'qse': 'qse_name'}, inplace=True)

merged_data = merged_data.merge(
    gen_resource_data_as,
    on=['delivery_date', 'hour_ending', 'qse_name', 'resource_name', 'dme',
        'p_posted_date'],
    how='left'
)

In [100]:
merged_data

,delivery_date,hour_ending,settlement_point,qse_name,energy_only_offer_award_in_mw,settlement_point_price,offer_id,p_posted_date,energy_only_offer_mw1,energy_only_offer_price1,...,price5_rrspfr,price5_rrsffr,price5_rrsufr,price5_ecrs,price5_offec,price5_online_nonspin,price5_regup,price5_regdown,price5_offline_nonspin,quantity_mw5
0,2024-10-02,1,ARAGORN_RN,QAEN,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-10-02,1,BOOTLEG_UN1,QAEN,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-10-02,1,DECKER_GT,QAEN,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-10-02,1,DECKER_GT,QAEN,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-10-02,1,DECKER_GT,QAEN,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94867,2024-10-02,24,WHCCS2_4,QZANDY,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94868,2024-10-02,24,WHCCS2_4,QZANDY,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94869,2024-10-02,24,WHCCS2_4,QZANDY,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94870,2024-10-02,24,WHCCS2_4,QZANDY,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94871,2024-10-02,24,CROSSETT_ALL,QZEPHY,NaN,NaN,NaN,2024-12-01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
load_resource_data = dataframes['df_dam_load_resource_data_60d']

load_resource_data.head()

,delivery_date,hour_ending,load_resource_name,max_power_consumption_for_load_resource,low_power_consumption_for_load_resource,regup_awarded,regup_mcpc,regdown_awarded,regdown_mcpc,rrs_awarded,rrs_mcpc,nonspin_awarded,nonspin_mcpc,rrspfr_awarded,rrsffr_awarded,rrsufr_awarded,ecrssd_awarded,ecrsmd_awarded,ecrs_mcpc,p_posted_date
0,2024-10-02,1,AAPIPLNC_LD3,24.0,0.0,0.0,1.12,0.0,0.79,NaN,0.75,0.0,0.2,0.0,0.0,0.0,0.0,7.0,0.05,2024-12-01
1,2024-10-02,1,AAPIPLNC_LD4,15.0,0.0,0.0,1.12,0.0,0.79,NaN,0.75,0.0,0.2,0.0,0.0,0.0,0.0,3.0,0.05,2024-12-01
2,2024-10-02,1,AIRPK_LD2,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
3,2024-10-02,1,AIRPK_LD3,2.9,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
4,2024-10-02,1,AIRPK_LD4,10.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16099,2024-10-02,24,WXOCF_LD3,23.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
16100,2024-10-02,24,W_HARLIN_LD1,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
16101,2024-10-02,24,X4_LD1,10.0,0.0,0.0,0.85,5.0,0.69,NaN,0.79,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.07,2024-12-01
16102,2024-10-02,24,YATES_LD1,5.1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
16103,2024-10-02,24,ZIER_SLR_LD1,34.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01

In [102]:
load_resource_data_as = dataframes['df_dam_load_resource_asoffers_60d']

load_resource_data_as.head()

,delivery_date,hour_ending,qse,dme,load_resource_name,multi_hour_block_flag,block_indicator1,price1_rrspfr,price1_rrsffr,price1_rrsufr,...,price5_rrsufr,price5_ecrs,price5_offec,price5_online_nonspin,price5_regup,price5_regdown,price5_offline_nonspin,quantity_mw5,nclr_flag,p_posted_date
0,2024-10-02,1,QEDE20,NaN,AAPIPLNC_LD3,N,V,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
1,2024-10-02,1,QEDE20,NaN,AAPIPLNC_LD4,N,V,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
2,2024-10-02,1,QEDE20,NaN,ALK_LD1,N,V,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
3,2024-10-02,1,QEDE20,NaN,ALK_LD2,N,V,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
4,2024-10-02,1,QSUE74,YSUEZ,ALVIN_LD1,N,V,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7245,2024-10-02,24,QENDU2,NaN,WILDCAT_LD4,N,V,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
7246,2024-10-02,24,QENDU2,NaN,WILDCAT_LD5,N,V,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
7247,2024-10-02,24,QENRWI,NaN,WMMMR_LD1,N,V,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
7248,2024-10-02,24,QEDE20,NaN,WRN_LD4,N,V,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01
7249,2024-10-02,24,QCPSE,YCPS,X4_LD1,N,V,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-01

In [ ]:
l